### ISSUE TITLE
修改用户名和密码

### ISSUE THREAD

**Issue by wangjueszu** [xyhelper/xyhelper-arkose#5]
这东西蛮有意思的，问题怎么修改用户名和密码呢？麻烦告知下，谢谢了

**Comment by gcslaoli** [comment]
哪个位置的用户名密码。。

**Comment by wangjueszu** [comment]
4. 管理chrome
登陆地址：[https://服务器IP:6901](https://xn--ip-fr5c86lx7z:6901/)

用户名：kasm_user

默认密码：xyhelper

这个的。

**Comment by gcslaoli** [comment]
> 4. 管理chrome
>        登陆地址：[https://服务器IP:6901](https://xn--ip-fr5c86lx7z:6901/)
> 
> 
> 用户名：kasm_user
> 
> 默认密码：xyhelper
> 
> 这个的。

用户名是固定的 密码在  docker-compose.yml 中修改 VNC_PW=xyhelper
